### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by znicholls** [GranthamImperial/silicone#103]
All the links point to znicholls/silicone, should be updated to point to the right place (might also require updating readthedocs etc...).

**Comment by Rlamboll** [comment]
Mostly solved by #104. I assume the links on readthedocs will update themselves whenever it next pulls because of the redirect, but any idea how to make it look here in the first place?

**Comment by znicholls** [comment]
I think it's looking in the right place, we just have an error in the docs so they aren't building. I'll have a play now, can jump on a call at some point to go into detail if you want.
