### ISSUE TITLE
Update CHANGELOG

### ISSUE THREAD

**Issue by znicholls** [GranthamImperial/silicone#122]
Our CHANGELOG is not as informative as it could be. We should update it's format and try to make what is in each version as clear as possible. Example here https://gitlab.com/netcdf-scm/netcdf-scm/-/blob/master/CHANGELOG.rst

**Comment by Rlamboll** [comment]
Yes, it's probably sensible. I don't see that anyone will use things before v1.0.0 for anything now so we can reformat after that in the new year.
