### ISSUE TITLE
Speed up RMSClosest cruncher 

### ISSUE THREAD

**Issue by jkikstra** [GranthamImperial/silicone#141]
**Is your feature request related to a problem? Please describe.**

RMSClosest is currently running slower than QuantileRollingWindows. 
This difference becomes much larger with very big (e.g. ~1600 scenarios) infiller databases, where it can take minutes per scenarios.

**Describe the solution you'd like**

@znicholls proposed to add RMS closest infilling for multiple pathways at the same time. 
Instead of calculating RMS for each pathway, which seems to be the case now, great speed up could result from only having to to calculate the closest pathway once which would then be followed by infill all the required pathways simultaneously.

**Describe alternatives you've considered**

More parallelization, e.g. using the joblib wrapper, because not all cpu capactity is used currently (see screenshot, when many other background processes were also running). 
![image](https://user-images.githubusercontent.com/46967503/135715090-d5b1b4e4-1cb5-4a10-831a-8c2f8adc025f.png)

**Additional context**

This is in the context of RMSClosest being seen as the more suitable general cruncher for sets where e.g. minor PFC and HFC gases of which confidence that model input is solidly modelled and not so biased towards only a few pathways.
But, at the moment using RMSClosest on bigger datasets is computationally very expensive.

**Comment by Rlamboll** [comment]
My problem with solution 1 (if I understand it correctly) is that it requires us to restrict our set of data to only those with all required variables - if the closest pathway to the lead has CO2 and CF4 but we also want to infill C2F6, attempting both computations at once will only speed up if we ignore this pathway. Parallelisation should be easy and cheap to do, none of this code is particularly optimised for runtime. Is the infilling not done in parallel at the moment?

**Comment by znicholls** [comment]
Bugger @Rlamboll is making very good points. Back to the drawing board/using parallelisation for now.

**Comment by Rlamboll** [comment]
I have done a PR #142 which attempts to speed up the RMS without changing the functionality - I got a 5x speedup on a moderate-sized infilling problem not sure how that will scale and if it's good enough for your use-case anyway.

**Comment by znicholls** [comment]
Closed by #142
